#!/usr/bin/env bash
#
# Switch static/admin/config.yml between production and local development.
#
#   scripts/cms-config.sh local     point the CMS at a locally-run cms-auth-proxy
#   scripts/cms-config.sh prod      restore the committed production config
#   scripts/cms-config.sh status    show which is currently in place
#
# The local values are read from cms-auth-proxy/.env rather than hardcoded, so
# config.yml cannot drift out of step with the proxy. That matters: if
# `base_url` and the proxy's PUBLIC_URL differ by even a trailing slash, Decap
# compares the login popup's event.origin against base_url, ignores the
# mismatch, and the login hangs with nothing in the console.
#
# "prod" is simply `git checkout`, so the production config is whatever is
# committed - this script has no second copy of it to fall out of date.

set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="static/admin/config.yml"
ENV_FILE="cms-auth-proxy/.env"

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
warn()  { printf '\033[33m%s\033[0m\n' "$*"; }

current_backend() {
  sed -n '/^backend:/,/^[^ #]/p' "$CONFIG" | grep -E '^\s+(repo|base_url|api_root):' || true
}

is_local() { grep -qE '^\s+base_url:\s*http://localhost' "$CONFIG"; }

status() {
  echo "$CONFIG:"
  current_backend | sed 's/^/  /'
  echo
  if is_local; then
    warn "MODE: local  - this must NOT be committed."
    warn "             restore with: scripts/cms-config.sh prod"
  else
    green "MODE: production (matches the committed config)"
  fi
  if ! git diff --quiet -- "$CONFIG" 2>/dev/null; then
    echo
    warn "note: $CONFIG differs from the committed version."
  fi
}

case "${1:-status}" in

  local)
    [ -f "$ENV_FILE" ] || {
      red "No $ENV_FILE - the local values come from there."
      red "Create it first: cd cms-auth-proxy && cp env.local.template .env"
      exit 1
    }

    # Pull the proxy's own settings so the two cannot disagree.
    REPO=$(grep -E '^GITHUB_REPO=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"'"'"' ' || true)
    PUBLIC_URL=$(grep -E '^PUBLIC_URL=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"'"'"' ' || true)
    PUBLIC_URL="${PUBLIC_URL%/}"

    [ -n "$REPO" ]       || { red "GITHUB_REPO not set in $ENV_FILE"; exit 1; }
    [ -n "$PUBLIC_URL" ] || { red "PUBLIC_URL not set in $ENV_FILE";  exit 1; }

    # Start from the committed config so repeated runs cannot stack edits.
    git checkout -- "$CONFIG" 2>/dev/null || true

    REPO="$REPO" PUBLIC_URL="$PUBLIC_URL" python3 - "$CONFIG" <<'PY'
import os, re, sys, pathlib
p = pathlib.Path(sys.argv[1])
s = p.read_text()
repo, base = os.environ["REPO"], os.environ["PUBLIC_URL"]

header = f"""backend:
  name: github
  # ---- LOCAL DEVELOPMENT - DO NOT COMMIT ----------------------------------
  # Generated by scripts/cms-config.sh from cms-auth-proxy/.env
  # Restore before committing:  scripts/cms-config.sh prod
  repo: {repo}
  branch: main
  base_url: {base}
  auth_endpoint: auth
  api_root: {base}/github
  # -------------------------------------------------------------------------

publish_mode: editorial_workflow

"""
# Everything from logo_url onwards (collections etc) is untouched.
p.write_text(header + s[s.index("logo_url:"):])
PY

    green "Switched to LOCAL:"
    current_backend | sed 's/^/  /'
    echo
    echo "Next:"
    echo "  1. cd cms-auth-proxy && npm start        (proxy on ${PUBLIC_URL})"
    echo "  2. npm run develop                       (site on :8000)"
    echo "  3. open http://localhost:8000/admin/index.html"
    echo
    warn "Remember: scripts/cms-config.sh prod  before committing."
    ;;

  prod)
    git checkout -- "$CONFIG"
    green "Restored the committed production config:"
    current_backend | sed 's/^/  /'
    ;;

  status) status ;;

  *)
    echo "usage: scripts/cms-config.sh [local|prod|status]"
    exit 1
    ;;
esac
